[build]
target = "x86_64-pc-windows-msvc"

[target.aarch64-linux-android]
linker = 'C:\Users\jjthe\AppData\Local\Android\Sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android35-clang.cmd'
rustflags = [
    "-C",
    "link-arg=-landroid",
    "-C",
    "link-arg=-llog",
]

[target.armv7-linux-androideabi]
linker = 'C:\Users\jjthe\AppData\Local\Android\Sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\armv7a-linux-androideabi35-clang.cmd'
rustflags = [
    "-C",
    "link-arg=-landroid",
    "-C",
    "link-arg=-llog",
]

[target.i686-linux-android]
linker = 'C:\Users\jjthe\AppData\Local\Android\Sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\i686-linux-android35-clang.cmd'
rustflags = [
    "-C",
    "link-arg=-landroid",
    "-C",
    "link-arg=-llog",
]
